### PR TITLE
图片梗和文字梗切换

### PR DESCRIPTION
**Pull request by shikukuya**

### CODE REVIEW

**Review by NCBM — CHANGES_REQUESTED** [review]
Nice work.

But all contents in `text/` should be generated by the script automatically, which means that what you should edit are the scripts in `shell/` and the source article in `art/`. Changes in `text/` will be overridden as source contents update.

**Comment by shikukuya** [comment]
> Nice work.
> 
> But all contents in `text/` should be generated by the script automatically, which means that what you should edit are the scripts in `shell/` and the source article in `art/`. Changes in `text/` will be overridden as source contents update.

image

**Comment by NCBM** [comment]
> > Nice work.
> > But all contents in `text/` should be generated by the script automatically, which means that what you should edit are the scripts in `shell/` and the source article in `art/`. Changes in `text/` will be overridden as source contents update.
> 
> image

I mean this:

Screenshot_20230113_155730

You only changed the product page, not the source.

**Comment by NCBM** [comment]
Well, I'll merge it and fix the source article manually.

**Pull request merged**
